databases:
  - name: project-db
    databaseName: project_db
    plan: free

services:
  - type: web
    name: project-manager
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:application
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: "3.11.0"
    plan: free
